\newcommand{\ve}[1]{\boldsymbol{#1}}		% Жирный вектор

\newcommand{\dd} [2]{\frac{d #1}{d #2}}
\newcommand{\pdd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\ddc}[3]{\left( \frac{\partial #1}{\partial #2} \right)_{\! #3}}
\newcommand{\abs}[1]{\left| #1 \right|}
\newcommand{\divc}  {\mathop{\raisebox{-2pt}{\vdots}}}

\renewcommand{\iff}     {\quad \Longleftrightarrow \quad}
\newcommand  {\then}    {\quad \Longrightarrow \quad}
\newcommand  {\subst}[1]{\begin{Vmatrix} #1 \end{Vmatrix}}

% \newcommand  {\qed}     {\hfill\ensuremath{\blacksquare}}

\newcommand  {\const}{\ensuremath{\mathrm{const}}}

\renewcommand{\Im}{\text{Im}}
\renewcommand{\Re}{\text{Re}}